channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.1.1
- pip:
  - mlflow==3.1.0
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - lightgbm==4.6.0
  - matplotlib==3.10.3
  - numpy==2.1.2
  - pandas==2.2.3
  - psutil==7.0.0
  - pyarrow==20.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
